import { SignUp } from '@clerk/nextjs'

// WE DID THIS BC THE auth PAGE (THE sign in ONE ONCE clerk WAS INTEGRATED) IS NOT WITHIN OUR localhost RN, WHICH MEANS WE HAVE TO CREATE ROUTE PAGES WITHIN OUR ROUTING STRUCTURE SO THAT THE sing in WINDOW APPEARS WITHIN OUR ROUTING STRUCTURE, THAT IS WHY WE ADD THE VARIABLES NEXT_PUBLIC_CLERK_SIGN_UP_URL AND NEXT_PUBLIC_CLERK_SIGN_IN_URL TO THE .env.local FILE
const SignUpPage = () => {
  return <SignUp />
}

export default SignUpPage